/* ==========================================================================
   Recipe library for the Weekly Meal Planner.

   STARTER_RECIPES seed the user's repository on first launch so the app is
   useful immediately — they can be edited or deleted like any other recipe.

   DISCOVER_LIBRARY is the pool the weekly "2 new recipe" suggestions are
   drawn from. Each entry carries tags and ingredients so suggestions can be
   scored against what the user already cooks.

   meal: "lunch" | "dinner" | "both" — which plan slots a recipe may fill.
   Ingredient shape: { item, qty, unit, category }
   qty is per the recipe's stated servings; category drives grocery grouping.
   ========================================================================== */

const STARTER_RECIPES = [
  {
    name: "Lemon Garlic Chicken",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "quick", "weeknight"],
    ingredients: [
      { item: "chicken breast", qty: 4, unit: "piece", category: "Meat & Seafood" },
      { item: "lemon", qty: 2, unit: "piece", category: "Produce" },
      { item: "garlic", qty: 4, unit: "clove", category: "Produce" },
      { item: "olive oil", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "butter", qty: 2, unit: "tbsp", category: "Dairy & Eggs" },
      { item: "fresh parsley", qty: 0.25, unit: "cup", category: "Produce" },
    ],
  },
  {
    name: "Spaghetti Bolognese",
    servings: 4,
    meal: "dinner",
    tags: ["pasta", "italian", "beef"],
    ingredients: [
      { item: "spaghetti", qty: 1, unit: "lb", category: "Pantry" },
      { item: "ground beef", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "crushed tomatoes", qty: 28, unit: "oz", category: "Pantry" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "garlic", qty: 3, unit: "clove", category: "Produce" },
      { item: "carrot", qty: 1, unit: "piece", category: "Produce" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "parmesan cheese", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Veggie Stir-Fry with Rice",
    servings: 2,
    meal: "both",
    tags: ["vegetarian", "asian", "quick"],
    ingredients: [
      { item: "jasmine rice", qty: 1, unit: "cup", category: "Pantry" },
      { item: "broccoli", qty: 2, unit: "cup", category: "Produce" },
      { item: "bell pepper", qty: 1, unit: "piece", category: "Produce" },
      { item: "carrot", qty: 1, unit: "piece", category: "Produce" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 2, unit: "clove", category: "Produce" },
      { item: "fresh ginger", qty: 1, unit: "tbsp", category: "Produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "Pantry" },
    ],
  },
  {
    name: "Sheet-Pan Salmon & Asparagus",
    servings: 2,
    meal: "dinner",
    tags: ["fish", "healthy", "quick"],
    ingredients: [
      { item: "salmon fillet", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "asparagus", qty: 1, unit: "bunch", category: "Produce" },
      { item: "lemon", qty: 1, unit: "piece", category: "Produce" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 2, unit: "clove", category: "Produce" },
    ],
  },
  {
    name: "Beef Tacos",
    servings: 4,
    meal: "both",
    tags: ["mexican", "beef", "weeknight"],
    ingredients: [
      { item: "ground beef", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "taco shells", qty: 8, unit: "piece", category: "Pantry" },
      { item: "cheddar cheese", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "lettuce", qty: 2, unit: "cup", category: "Produce" },
      { item: "tomato", qty: 2, unit: "piece", category: "Produce" },
      { item: "taco seasoning", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Chicken Caesar Salad",
    servings: 2,
    meal: "lunch",
    tags: ["chicken", "salad", "healthy", "quick"],
    ingredients: [
      { item: "chicken breast", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "romaine lettuce", qty: 1, unit: "head", category: "Produce" },
      { item: "caesar dressing", qty: 0.33, unit: "cup", category: "Pantry" },
      { item: "parmesan cheese", qty: 0.33, unit: "cup", category: "Dairy & Eggs" },
      { item: "croutons", qty: 1, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Creamy Tomato Soup & Grilled Cheese",
    servings: 2,
    meal: "both",
    tags: ["vegetarian", "comfort", "soup"],
    ingredients: [
      { item: "crushed tomatoes", qty: 28, unit: "oz", category: "Pantry" },
      { item: "heavy cream", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "garlic", qty: 2, unit: "clove", category: "Produce" },
      { item: "sourdough bread", qty: 4, unit: "slice", category: "Bakery" },
      { item: "cheddar cheese", qty: 4, unit: "slice", category: "Dairy & Eggs" },
      { item: "butter", qty: 2, unit: "tbsp", category: "Dairy & Eggs" },
    ],
  },
];

const DISCOVER_LIBRARY = [
  {
    name: "Chicken Piccata",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "italian", "quick"],
    description: "Pan-fried chicken cutlets in a bright lemon-caper butter sauce.",
    ingredients: [
      { item: "chicken breast", qty: 4, unit: "piece", category: "Meat & Seafood" },
      { item: "lemon", qty: 2, unit: "piece", category: "Produce" },
      { item: "capers", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "butter", qty: 4, unit: "tbsp", category: "Dairy & Eggs" },
      { item: "flour", qty: 0.5, unit: "cup", category: "Pantry" },
      { item: "chicken broth", qty: 1, unit: "cup", category: "Pantry" },
      { item: "fresh parsley", qty: 0.25, unit: "cup", category: "Produce" },
    ],
  },
  {
    name: "Honey Garlic Glazed Salmon",
    servings: 2,
    meal: "dinner",
    tags: ["fish", "quick", "asian"],
    description: "Seared salmon lacquered with a sticky honey-garlic-soy glaze.",
    ingredients: [
      { item: "salmon fillet", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "honey", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "soy sauce", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 3, unit: "clove", category: "Produce" },
      { item: "lemon", qty: 1, unit: "piece", category: "Produce" },
      { item: "jasmine rice", qty: 1, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Chicken Tikka Masala",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "indian", "comfort"],
    description: "Yogurt-marinated chicken simmered in a creamy spiced tomato sauce.",
    ingredients: [
      { item: "chicken thigh", qty: 1.5, unit: "lb", category: "Meat & Seafood" },
      { item: "plain yogurt", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "crushed tomatoes", qty: 28, unit: "oz", category: "Pantry" },
      { item: "heavy cream", qty: 0.75, unit: "cup", category: "Dairy & Eggs" },
      { item: "garam masala", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 4, unit: "clove", category: "Produce" },
      { item: "fresh ginger", qty: 2, unit: "tbsp", category: "Produce" },
      { item: "basmati rice", qty: 1.5, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Shrimp Scampi Linguine",
    servings: 4,
    meal: "dinner",
    tags: ["pasta", "italian", "seafood", "quick"],
    description: "Garlicky shrimp tossed with linguine, white wine, lemon, and parsley.",
    ingredients: [
      { item: "shrimp", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "linguine", qty: 12, unit: "oz", category: "Pantry" },
      { item: "garlic", qty: 5, unit: "clove", category: "Produce" },
      { item: "butter", qty: 4, unit: "tbsp", category: "Dairy & Eggs" },
      { item: "white wine", qty: 0.5, unit: "cup", category: "Pantry" },
      { item: "lemon", qty: 1, unit: "piece", category: "Produce" },
      { item: "fresh parsley", qty: 0.25, unit: "cup", category: "Produce" },
    ],
  },
  {
    name: "Beef & Broccoli Stir-Fry",
    servings: 4,
    meal: "dinner",
    tags: ["beef", "asian", "quick"],
    description: "Takeout-style flank steak and broccoli in a glossy ginger-soy sauce.",
    ingredients: [
      { item: "flank steak", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "broccoli", qty: 4, unit: "cup", category: "Produce" },
      { item: "soy sauce", qty: 0.33, unit: "cup", category: "Pantry" },
      { item: "fresh ginger", qty: 1, unit: "tbsp", category: "Produce" },
      { item: "garlic", qty: 3, unit: "clove", category: "Produce" },
      { item: "cornstarch", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "jasmine rice", qty: 1.5, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Margherita Flatbread Pizza",
    servings: 2,
    meal: "both",
    tags: ["vegetarian", "italian", "quick"],
    description: "Crisp flatbreads with fresh mozzarella, tomatoes, and basil.",
    ingredients: [
      { item: "flatbread", qty: 2, unit: "piece", category: "Bakery" },
      { item: "fresh mozzarella", qty: 8, unit: "oz", category: "Dairy & Eggs" },
      { item: "tomato", qty: 2, unit: "piece", category: "Produce" },
      { item: "fresh basil", qty: 0.5, unit: "cup", category: "Produce" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 2, unit: "clove", category: "Produce" },
    ],
  },
  {
    name: "Slow-Cooker Pulled Pork Sandwiches",
    servings: 6,
    meal: "both",
    tags: ["pork", "comfort", "american"],
    description: "Fork-tender BBQ pulled pork piled on toasted buns with slaw.",
    ingredients: [
      { item: "pork shoulder", qty: 3, unit: "lb", category: "Meat & Seafood" },
      { item: "bbq sauce", qty: 1.5, unit: "cup", category: "Pantry" },
      { item: "burger buns", qty: 6, unit: "piece", category: "Bakery" },
      { item: "coleslaw mix", qty: 4, unit: "cup", category: "Produce" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
    ],
  },
  {
    name: "Greek Chicken Bowls",
    servings: 4,
    meal: "both",
    tags: ["chicken", "mediterranean", "healthy"],
    description: "Marinated chicken over rice with cucumber, feta, olives, and tzatziki.",
    ingredients: [
      { item: "chicken thigh", qty: 1.5, unit: "lb", category: "Meat & Seafood" },
      { item: "basmati rice", qty: 1.5, unit: "cup", category: "Pantry" },
      { item: "cucumber", qty: 1, unit: "piece", category: "Produce" },
      { item: "cherry tomatoes", qty: 1, unit: "cup", category: "Produce" },
      { item: "feta cheese", qty: 0.75, unit: "cup", category: "Dairy & Eggs" },
      { item: "kalamata olives", qty: 0.5, unit: "cup", category: "Pantry" },
      { item: "tzatziki", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "lemon", qty: 1, unit: "piece", category: "Produce" },
    ],
  },
  {
    name: "Mushroom Risotto",
    servings: 4,
    meal: "dinner",
    tags: ["vegetarian", "italian", "comfort"],
    description: "Creamy arborio rice with sautéed mushrooms and parmesan.",
    ingredients: [
      { item: "arborio rice", qty: 1.5, unit: "cup", category: "Pantry" },
      { item: "mushrooms", qty: 1, unit: "lb", category: "Produce" },
      { item: "vegetable broth", qty: 6, unit: "cup", category: "Pantry" },
      { item: "parmesan cheese", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "white wine", qty: 0.5, unit: "cup", category: "Pantry" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "butter", qty: 3, unit: "tbsp", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Fish Tacos with Lime Crema",
    servings: 4,
    meal: "both",
    tags: ["fish", "mexican", "quick"],
    description: "Crispy spiced white fish in warm tortillas with cabbage and lime crema.",
    ingredients: [
      { item: "cod fillet", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "corn tortillas", qty: 8, unit: "piece", category: "Pantry" },
      { item: "red cabbage", qty: 2, unit: "cup", category: "Produce" },
      { item: "lime", qty: 2, unit: "piece", category: "Produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
      { item: "chili powder", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "avocado", qty: 1, unit: "piece", category: "Produce" },
    ],
  },
  {
    name: "Thai Red Curry with Chicken",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "thai", "asian"],
    description: "Coconut red curry with chicken, bell pepper, and bamboo shoots over rice.",
    ingredients: [
      { item: "chicken thigh", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "red curry paste", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "coconut milk", qty: 14, unit: "oz", category: "Pantry" },
      { item: "bell pepper", qty: 1, unit: "piece", category: "Produce" },
      { item: "bamboo shoots", qty: 8, unit: "oz", category: "Pantry" },
      { item: "fresh basil", qty: 0.5, unit: "cup", category: "Produce" },
      { item: "jasmine rice", qty: 1.5, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Stuffed Bell Peppers",
    servings: 4,
    meal: "dinner",
    tags: ["beef", "comfort", "american"],
    description: "Bell peppers baked with a savory beef, rice, and tomato filling.",
    ingredients: [
      { item: "bell pepper", qty: 4, unit: "piece", category: "Produce" },
      { item: "ground beef", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "jasmine rice", qty: 1, unit: "cup", category: "Pantry" },
      { item: "crushed tomatoes", qty: 14, unit: "oz", category: "Pantry" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "cheddar cheese", qty: 1, unit: "cup", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Caprese Chicken Skillet",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "italian", "healthy", "quick"],
    description: "Seared chicken topped with mozzarella, tomatoes, basil, and balsamic glaze.",
    ingredients: [
      { item: "chicken breast", qty: 4, unit: "piece", category: "Meat & Seafood" },
      { item: "fresh mozzarella", qty: 8, unit: "oz", category: "Dairy & Eggs" },
      { item: "cherry tomatoes", qty: 2, unit: "cup", category: "Produce" },
      { item: "fresh basil", qty: 0.5, unit: "cup", category: "Produce" },
      { item: "balsamic glaze", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "Pantry" },
    ],
  },
  {
    name: "Black Bean Quesadillas",
    servings: 2,
    meal: "lunch",
    tags: ["vegetarian", "mexican", "quick"],
    description: "Crispy tortillas stuffed with black beans, corn, and melty cheese.",
    ingredients: [
      { item: "flour tortillas", qty: 4, unit: "piece", category: "Pantry" },
      { item: "black beans", qty: 15, unit: "oz", category: "Pantry" },
      { item: "corn", qty: 1, unit: "cup", category: "Frozen" },
      { item: "cheddar cheese", qty: 1.5, unit: "cup", category: "Dairy & Eggs" },
      { item: "salsa", qty: 0.75, unit: "cup", category: "Pantry" },
      { item: "avocado", qty: 1, unit: "piece", category: "Produce" },
    ],
  },
  {
    name: "Garlic Butter Steak Bites & Potatoes",
    servings: 4,
    meal: "dinner",
    tags: ["beef", "comfort", "quick"],
    description: "Sirloin bites and crispy potatoes tossed in garlic-herb butter.",
    ingredients: [
      { item: "sirloin steak", qty: 1.5, unit: "lb", category: "Meat & Seafood" },
      { item: "baby potatoes", qty: 1.5, unit: "lb", category: "Produce" },
      { item: "butter", qty: 4, unit: "tbsp", category: "Dairy & Eggs" },
      { item: "garlic", qty: 5, unit: "clove", category: "Produce" },
      { item: "fresh parsley", qty: 0.25, unit: "cup", category: "Produce" },
    ],
  },
  {
    name: "Coconut Chickpea Curry",
    servings: 4,
    meal: "both",
    tags: ["vegetarian", "indian", "healthy"],
    description: "Chickpeas and spinach simmered in a gingery coconut-tomato sauce.",
    ingredients: [
      { item: "chickpeas", qty: 30, unit: "oz", category: "Pantry" },
      { item: "coconut milk", qty: 14, unit: "oz", category: "Pantry" },
      { item: "crushed tomatoes", qty: 14, unit: "oz", category: "Pantry" },
      { item: "spinach", qty: 4, unit: "cup", category: "Produce" },
      { item: "curry powder", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "garlic", qty: 3, unit: "clove", category: "Produce" },
      { item: "fresh ginger", qty: 1, unit: "tbsp", category: "Produce" },
      { item: "basmati rice", qty: 1.5, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Pesto Pasta with Roasted Vegetables",
    servings: 4,
    meal: "both",
    tags: ["vegetarian", "pasta", "italian"],
    description: "Penne tossed with basil pesto, roasted zucchini, and cherry tomatoes.",
    ingredients: [
      { item: "penne pasta", qty: 12, unit: "oz", category: "Pantry" },
      { item: "basil pesto", qty: 0.75, unit: "cup", category: "Pantry" },
      { item: "zucchini", qty: 2, unit: "piece", category: "Produce" },
      { item: "cherry tomatoes", qty: 2, unit: "cup", category: "Produce" },
      { item: "parmesan cheese", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
      { item: "olive oil", qty: 2, unit: "tbsp", category: "Pantry" },
    ],
  },
  {
    name: "Chicken Fried Rice",
    servings: 4,
    meal: "both",
    tags: ["chicken", "asian", "quick"],
    description: "Wok-fried rice with chicken, egg, peas, and scallions.",
    ingredients: [
      { item: "chicken breast", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "jasmine rice", qty: 2, unit: "cup", category: "Pantry" },
      { item: "eggs", qty: 3, unit: "piece", category: "Dairy & Eggs" },
      { item: "frozen peas", qty: 1, unit: "cup", category: "Frozen" },
      { item: "soy sauce", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "scallions", qty: 4, unit: "piece", category: "Produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "Pantry" },
    ],
  },
  {
    name: "Turkey Chili",
    servings: 6,
    meal: "both",
    tags: ["turkey", "comfort", "american", "soup"],
    description: "Hearty ground-turkey chili with beans, warm spices, and all the toppings.",
    ingredients: [
      { item: "ground turkey", qty: 1.5, unit: "lb", category: "Meat & Seafood" },
      { item: "kidney beans", qty: 30, unit: "oz", category: "Pantry" },
      { item: "crushed tomatoes", qty: 28, unit: "oz", category: "Pantry" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "chili powder", qty: 3, unit: "tbsp", category: "Pantry" },
      { item: "cheddar cheese", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Baked Ziti",
    servings: 6,
    meal: "dinner",
    tags: ["pasta", "italian", "comfort", "beef"],
    description: "Bubbly baked pasta layered with meat sauce, ricotta, and mozzarella.",
    ingredients: [
      { item: "ziti pasta", qty: 1, unit: "lb", category: "Pantry" },
      { item: "ground beef", qty: 1, unit: "lb", category: "Meat & Seafood" },
      { item: "marinara sauce", qty: 32, unit: "oz", category: "Pantry" },
      { item: "ricotta cheese", qty: 15, unit: "oz", category: "Dairy & Eggs" },
      { item: "shredded mozzarella", qty: 2, unit: "cup", category: "Dairy & Eggs" },
      { item: "garlic", qty: 3, unit: "clove", category: "Produce" },
    ],
  },
  {
    name: "Miso-Glazed Cod with Bok Choy",
    servings: 2,
    meal: "dinner",
    tags: ["fish", "asian", "healthy"],
    description: "Broiled cod with a sweet-savory miso glaze and sesame bok choy.",
    ingredients: [
      { item: "cod fillet", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "miso paste", qty: 2, unit: "tbsp", category: "Pantry" },
      { item: "honey", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "bok choy", qty: 2, unit: "head", category: "Produce" },
      { item: "sesame oil", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "jasmine rice", qty: 1, unit: "cup", category: "Pantry" },
    ],
  },
  {
    name: "Chicken Enchiladas",
    servings: 4,
    meal: "dinner",
    tags: ["chicken", "mexican", "comfort"],
    description: "Rolled tortillas with shredded chicken, smothered in red sauce and cheese.",
    ingredients: [
      { item: "chicken breast", qty: 3, unit: "piece", category: "Meat & Seafood" },
      { item: "flour tortillas", qty: 8, unit: "piece", category: "Pantry" },
      { item: "enchilada sauce", qty: 20, unit: "oz", category: "Pantry" },
      { item: "shredded mozzarella", qty: 2, unit: "cup", category: "Dairy & Eggs" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "sour cream", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
    ],
  },
  {
    name: "Lentil Soup with Crusty Bread",
    servings: 4,
    meal: "lunch",
    tags: ["vegetarian", "soup", "healthy", "comfort"],
    description: "Rustic lentil-vegetable soup finished with lemon, served with warm bread.",
    ingredients: [
      { item: "green lentils", qty: 1.5, unit: "cup", category: "Pantry" },
      { item: "carrot", qty: 2, unit: "piece", category: "Produce" },
      { item: "celery", qty: 2, unit: "stalk", category: "Produce" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "vegetable broth", qty: 6, unit: "cup", category: "Pantry" },
      { item: "lemon", qty: 1, unit: "piece", category: "Produce" },
      { item: "sourdough bread", qty: 4, unit: "slice", category: "Bakery" },
    ],
  },
  {
    name: "BBQ Chicken Flatbreads",
    servings: 2,
    meal: "lunch",
    tags: ["chicken", "american", "quick"],
    description: "Flatbreads with BBQ chicken, red onion, cheddar, and cilantro.",
    ingredients: [
      { item: "chicken breast", qty: 2, unit: "piece", category: "Meat & Seafood" },
      { item: "flatbread", qty: 2, unit: "piece", category: "Bakery" },
      { item: "bbq sauce", qty: 0.5, unit: "cup", category: "Pantry" },
      { item: "red onion", qty: 0.5, unit: "piece", category: "Produce" },
      { item: "cheddar cheese", qty: 1, unit: "cup", category: "Dairy & Eggs" },
      { item: "fresh cilantro", qty: 0.25, unit: "cup", category: "Produce" },
    ],
  },
  {
    name: "Pork Chops with Apples & Onions",
    servings: 4,
    meal: "dinner",
    tags: ["pork", "american", "comfort"],
    description: "Pan-seared pork chops with cider-glazed apples and onions.",
    ingredients: [
      { item: "pork chop", qty: 4, unit: "piece", category: "Meat & Seafood" },
      { item: "apple", qty: 2, unit: "piece", category: "Produce" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "apple cider", qty: 0.75, unit: "cup", category: "Pantry" },
      { item: "butter", qty: 2, unit: "tbsp", category: "Dairy & Eggs" },
      { item: "fresh thyme", qty: 1, unit: "tbsp", category: "Produce" },
    ],
  },
  {
    name: "Shakshuka",
    servings: 2,
    meal: "lunch",
    tags: ["vegetarian", "mediterranean", "eggs", "quick"],
    description: "Eggs poached in a spiced tomato-pepper sauce with feta and warm pita.",
    ingredients: [
      { item: "eggs", qty: 4, unit: "piece", category: "Dairy & Eggs" },
      { item: "crushed tomatoes", qty: 28, unit: "oz", category: "Pantry" },
      { item: "bell pepper", qty: 1, unit: "piece", category: "Produce" },
      { item: "onion", qty: 1, unit: "piece", category: "Produce" },
      { item: "feta cheese", qty: 0.5, unit: "cup", category: "Dairy & Eggs" },
      { item: "smoked paprika", qty: 1, unit: "tbsp", category: "Pantry" },
      { item: "pita bread", qty: 2, unit: "piece", category: "Bakery" },
    ],
  },
];
